### ISSUE TITLE
ReferenceError: URLSearchParams is not defined

### ISSUE THREAD

**Issue by hobbs** [gja/create-cloudflare-worker#2]
Here are the steps I took:
```
npm init cloudflare-worker helloworld
cd helloworld
npm run build
npm test
npm start
```

The tests pass, but when I try to load `http://localhost:4000/` I get the following in the log:
```
Example app listening on port 4000!
ReferenceError: URLSearchParams is not defined
    at Worker.evaluateWorkerContents (/home/zach/src/workers/helloworld/node_modules/cloudflare-worker-local/app/worker.js:74:7)
    at new Worker (/home/zach/src/workers/helloworld/node_modules/cloudflare-worker-local/app/worker.js:65:10)
    at app.use (/home/zach/src/workers/helloworld/node_modules/cloudflare-worker-local/app/server.js:39:60)
    at Layer.handle [as handle_request] (/home/zach/src/workers/helloworld/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/zach/src/workers/helloworld/node_modules/express/lib/router/index.js:317:13)
    at /home/zach/src/workers/helloworld/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/home/zach/src/workers/helloworld/node_modules/express/lib/router/index.js:335:12)
    at next (/home/zach/src/workers/helloworld/node_modules/express/lib/router/index.js:275:10)
    at rawParser (/home/zach/src/workers/helloworld/node_modules/body-parser/lib/types/raw.js:67:7)
    at Layer.handle [as handle_request] (/home/zach/src/workers/helloworld/node_modules/express/lib/router/layer.js:95:5)
```

Using ubuntu 18.04, with nodejs provided by ubuntu (8.11.4)

**Comment by hobbs** [comment]
Fixed by using npm provided `node` (11.9.0)
